name: dart_testing
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.0

# Add regular dependencies here.
dependencies:
  json_annotation: ^4.8.0
  dotenv: ^4.2.0
  dart_firebase_admin: ^0.4.0
  uuid: ^4.5.1
  http: ^1.3.0
  dart_geohash: ^2.1.0
  json_serializable: ^6.7.0
  excel: ^4.0.6

dev_dependencies:
  lints: ^5.0.0
  very_good_analysis: ^7.0.0
  build_runner: ^2.4.7
  test: ^1.24.0
